### PR TITLE
Dorian test

### PR DESCRIPTION
**Pull request by datovard**
Adding my attempt on the Instastore Backend technical challenge
@davidcp90 @

### CODE REVIEW

**Review by joagranadosme — CHANGES_REQUESTED** [review]
This is just bad

**Comment by datovard** [comment]
> This is just bad

🖕🏻

**Comment by osdajigu** [comment]
Come on, merge this PR or close it 🥺

**Comment by datovard** [comment]
> Come on, merge this PR or close it pleading_face

I can't merge this PR :v

**Comment by osdajigu** [comment]
Then close it haha

**Review by osdajigu — APPROVED** [review]
Best PR seen ever

**Comment by datovard** [comment]
> Best PR seen ever

To close it would be a complete waste ✨

**Comment by osdajigu** [comment]
LGTM

**Comment by osdajigu** [comment]
Come on!, merge it now!

**Review by osdajigu — APPROVED** [review]

**Review by osdajigu — CHANGES_REQUESTED** [review]
very terrible

**Comment by datovard** [comment]
Going to close it :v

**Comment by osdajigu** [comment]
Finally

**Pull request closed without merging**
